
default:
  image: node:latest
  before_script:
    - |
      {
        echo "@miniapp:registry=${CI_API_V4_URL}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
        echo "registry=https://registry.npmmirror.com/"
      } | tee --append .npmrc
    - npm install -g pnpm@latest-8 --force
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

#workflow:
#  rules:
#    - if: $CI_COMMIT_BRANCH


# 环境变量
variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}


# 定义构建流程
stages:
  - deploy
  # - notification


# 部署到 Kubernetes 集群 - 测试环境
deploy:
  stage: deploy
  only:
    - main
  script:
    - sh ./ADAPT.sh


# 构建完成的消息通知
# notification:
#   stage: notification
#   only:
#     - main
#   script:
#     - latestTag=$(git describe --tags $(git rev-list --tags --max-count=1))
#     - >-
#       curl 'https://oapi.dingtalk.com/robot/send?access_token='$DINGTALK_AT_WEB''
#       -H 'Content-Type: application/json'
#       -d '{
#             "msgtype": "actionCard",
#             "actionCard": {
#               "title": "'$CI_PROJECT_NAME' '$CI_COMMIT_TAG'版本发布成功",
#               "text": "![npm](https://image.biubiukam.com/kk/npm/npm-template.png)  \n\n#### '$CI_PROJECT_NAME' 发布成功  \n发布版本: **'$latestTag'**，请使用本包开发者自行选择对应版本更新。",
#               "btnOrientation": "1",
#               "btns": [
#                 {
#                     "title": "更新记录",
#                     "actionURL": "dingtalk://dingtalkclient/page/link?url=https%3A%2F%2Fgit.kkgroup.cn%2Ffeb%2F'$CI_PROJECT_NAME'%2F-%2Fblob%2Freleased%2FCHANGELOG.md&pc_slide=false"
#                 },
#                 {
#                     "title": "项目说明",
#                     "actionURL": "dingtalk://dingtalkclient/page/link?url=https%3A%2F%2Fgit.kkgroup.cn%2Ffeb%2F'$CI_PROJECT_NAME'%2F-%2Fblob%2Freleased%2FREADME.md&pc_slide=false"
#                 }
#               ]
#             },
#             "at": {
#                 "atMobiles": [],
#                 "isAtAll": false
#             }
#           }'
